### ISSUE TITLE
Integrate into Sequel

### ISSUE THREAD

**Issue by jeremyevans** [QuinnHarris/sequel-table_inheritance#1]
@QuinnHarris could you submit a pull request to Sequel to replace the class_table_inheritance plugin with this plugin, since it is backwards compatible?  There wasn't any community feedback on the sequel-talk thread, but since there weren't any objections and I think it would be a useful addition, I'd like to include it with Sequel.

**Comment by QuinnHarris** [comment]
Sorry for the delay.  I failed to notice the message until recently.  I have put up a pull request against Sequel.
